=== farao-community/ce-merging-server/src/main/resources/xsd/internal_bz/biddingzoneuctedocument-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2026, RTE (http://www.rte-france.com)
  ~ This Source Code Form is subject to the terms of the Mozilla Public
  ~ License, v. 2.0. If a copy of the MPL was not distributed with this
  ~ file, You can obtain one at http://mozilla.org/MPL/2.0/.
  -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="etso-core-cmpts.xsd" schemaLocation="etso-core-cmpts.xsd" />
	<xsd:import namespace="etso-code-lists.xsd" schemaLocation="etso-code-lists.xsd" />

  <xsd:element name="BiddingZoneUCTEDocument">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="DocumentIdentification" type="ValueElementType"/>
        <xsd:element name="DocumentVersion" type="ValueElementType"/>
        <xsd:element name="DocumentType" type="ValueElementType"/>
        <xsd:element name="ProcessType" type="ValueElementType"/>
        <xsd:element name="SenderIdentification" type="CodingSchemeValueElementType"/>
        <xsd:element name="SenderRole" type="ValueElementType"/>
        <xsd:element name="ReceiverIdentification" type="CodingSchemeValueElementType"/>
        <xsd:element name="ReceiverRole" type="ValueElementType"/>
        <xsd:element name="CreationDateTime" type="ValueElementType"/>
        <xsd:element name="Internal_tie_lines" type="InternalTieLinesType"/>
        <xsd:element name="Bidding_zones" type="BiddingZonesType"/>
      </xsd:sequence>
      <xsd:attribute name="DtdRelease" type="xsd:string" use="required" fixed="0"/>
      <xsd:attribute name="DtdVersion" type="xsd:string" use="required" fixed="4"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="ValueElementType">
    <xsd:attribute name="v" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="CodingSchemeValueElementType">
    <xsd:attribute name="codingScheme" type="xsd:string" use="required"/>
    <xsd:attribute name="v" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="InternalTieLinesType">
    <xsd:sequence>
      <xsd:element name="Internal_tie_line" type="InternalTieLineType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="count" type="xsd:nonNegativeInteger" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="InternalTieLineType">
    <xsd:sequence>
      <xsd:element name="branch" type="BranchType"/>
      <xsd:element name="bidding_zone_from" type="TextOnlyType"/>
      <xsd:element name="bidding_zone_to" type="TextOnlyType"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:positiveInteger" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="BranchType">
    <xsd:attribute name="from" type="xsd:string" use="required"/>
    <xsd:attribute name="to" type="xsd:string" use="required"/>
    <xsd:attribute name="elementName" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="TextOnlyType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string"/>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="BiddingZonesType">
    <xsd:sequence>
      <xsd:element name="Bidding_zone" type="BiddingZoneType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="count" type="xsd:nonNegativeInteger" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="BiddingZoneType">
    <xsd:sequence>
      <xsd:element name="TimeInterval" type="ValueElementType"/>
      <xsd:element name="Area" type="CodingSchemeValueElementType"/>
      <xsd:element name="NodeName" type="ValueElementType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== farao-community/ce-merging-server/src/test/resources/request-metadata/inputs/biddingzoneucte.xml
<?xml version='1.0' encoding='utf-8'?>
<!--
  ~ Copyright (c) 2026, RTE (http://www.rte-france.com)
  ~ This Source Code Form is subject to the terms of the Mozilla Public
  ~ License, v. 2.0. If a copy of the MPL was not distributed with this
  ~ file, You can obtain one at http://mozilla.org/MPL/2.0/.
  -->

<BiddingZoneUCTEDocument DtdVersion="4" DtdRelease="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biddingzoneuctedocument-1.xsd">
  <DocumentIdentification v="17XTSO-CS------W-20260707F301v2" />
  <DocumentVersion v="2" />
  <DocumentType v="B06" />
  <ProcessType v="A01" />
  <SenderIdentification codingScheme="A01" v="17XTSO-CS------W" />
  <SenderRole v="A36" />
  <ReceiverIdentification codingScheme="A01" v="22XCORESO------S" />
  <ReceiverRole v="A44" />
  <CreationDateTime v="2026-07-05T19:17:09Z" />
  <Internal_tie_lines count="24">
    <Internal_tie_line id="1">
      <branch from="ICNOR12" to="INORD12" elementName="CN_N" />
      <bidding_zone_from>ICNO</bidding_zone_from>
      <bidding_zone_to>NORD</bidding_zone_to>
    </Internal_tie_line>
    <Internal_tie_line id="2">
      <branch from="ICNOR12" to="ICSUD12" elementName="CN_CS" />
      <bidding_zone_from>ICNO</bidding_zone_from>
      <bidding_zone_to>ICSO</bidding_zone_to>
    </Internal_tie_line>
    <Internal_tie_line id="3">
      <branch from="ICALA11" to="ICSUD12" elementName="CA_CS" />
      <bidding_zone_from>CALABRIA</bidding_zone_from>
      <bidding_zone_to>ICSO</bidding_zone_to>
    </Internal_tie_line>
    <Internal_tie_line id="4">
      <branch from="ISUDN11" to="ICSUD12" elementName="S_CS" />
      <bidding_zone_from>SUD</bidding_zone_from>
      <bidding_zone_to>ICSO</bidding_zone_to>
    </Internal_tie_line>
    <Internal_tie_line id="5">
      <branch from="ISUDN11" to="ICALA11" elementName="S_CA" />
      <bidding_zone_from>SUD</bidding_zone_from>
      <bidding_zone_to>CALABRIA</bidding_zone_to>
    </Internal_tie_line>
  </Internal_tie_lines>
  <Bidding_zones count="5">
    <Bidding_zone>
      <TimeInterval v="2026-07-06T22:00Z/2026-07-06T23:00Z" />
      <Area codingScheme="A01" v="ICNO" />
      <NodeName v="ICNOR12" />
    </Bidding_zone>
    <Bidding_zone>
      <TimeInterval v="2026-07-06T22:00Z/2026-07-06T23:00Z" />
      <Area codingScheme="A01" v="INOR" />
      <NodeName v="INORD12" />
    </Bidding_zone>
    <Bidding_zone>
      <TimeInterval v="2026-07-06T22:00Z/2026-07-06T23:00Z" />
      <Area codingScheme="A01" v="ICSO" />
      <NodeName v="ICSUD12" />
    </Bidding_zone>
    <Bidding_zone>
      <TimeInterval v="2026-07-06T22:00Z/2026-07-06T23:00Z" />
      <Area codingScheme="A01" v="ICAL" />
      <NodeName v="ICALA11" />
    </Bidding_zone>
    <Bidding_zone>
      <TimeInterval v="2026-07-06T22:00Z/2026-07-06T23:00Z" />
      <Area codingScheme="A01" v="ISOU" />
      <NodeName v="ISUDN11" />
    </Bidding_zone>
  </Bidding_zones>
</BiddingZoneUCTEDocument>
